### ISSUE TITLE
Make banner-body text stand out more

### ISSUE THREAD

**Issue by lscan** [lscan/Portfolio#1]
Could add something like:

```css
.banner-body {
  padding: 20px;
  background-color: rgb(235, 236, 238, .65);
  border-radius: 5px;
}
```

Or maybe the text styling just needs adjusting.
